language: groovy

jdk:
- oraclejdk7

branches:
  only:
  - master

services: memcached

script: ./grailsw test-app
  && cd test/apps
  && for app in `ls .`; do cd $app && ../../../grailsw test-app ; done
  && cd ../../../

after_success: ./doc.sh

env:
  global:
    secure: NDX1oObVIHhG5zUZzhmL8m/601SFB2pE29dci1EcgKrYhdZf+50+Va/b0/7lNzYXnT76CwQmdkbsJmwqBh6+YO+SXcJFE13zudyGfZhLOwY+/oueQB8Up/gk2WbkY4FdIlo0XP/jl+atz4gR9EoAnKCYbdcjYj2lQnJ8ocDpi5U=
