language: groovy

jdk:
- oraclejdk7
- oraclejdk8

branches:
  only:
  - master
  - develop
  - "/^release.*$/"
  - "/^feature.*$/"

services:
- memcached
- redis-server

install:
  - npm install divshot-cli -g

script: "./test-app.sh"

after_success: if [[ $TRAVIS_BRANCH == "master" ]] || [[ $TRAVIS_BRANCH =~ ^release.*$ ]]; then ./doc.sh; fi

after_script: "./publish-test-results.sh"

notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/ab2251f887cfa63260af
    on_success: change
    on_failure: always
    on_start: false
env:
  global:
  - secure: NDX1oObVIHhG5zUZzhmL8m/601SFB2pE29dci1EcgKrYhdZf+50+Va/b0/7lNzYXnT76CwQmdkbsJmwqBh6+YO+SXcJFE13zudyGfZhLOwY+/oueQB8Up/gk2WbkY4FdIlo0XP/jl+atz4gR9EoAnKCYbdcjYj2lQnJ8ocDpi5U=
  - secure: CI++zUthM/3TMRmEs4ngqJYrH8JMf8nKH71MP3Q4DeqrK8ktBt7HevdxLBy5a9KhYabgHdAmrFutJHtTcXlfMizytr/FVus7Dj6BNPZCTzesO8J/HVzzWQx6EofJoqBJp27AXh/mT290A1yS/WsoW0e1FuLWPIXJHXCa1wZQTU0=
  - secure: i+HYyyMe2qXPZkP113Vo+uXDzWeiS96dE8EiURxB75HDLuQ1UuIKkfZylNyWXcJHh8gy6ypKffxjZ0FeN44FQeiChE+WC20Xh9UOG076zHogFIE/IooFawau+jcvqJzQU+3koDO9zocu8HfULqenfapSKri/5vMxaPTj85VdFfk=
  - GIT_NAME = "Alvaro Sanchez-Mariscal"
  - GIT_EMAIL = "alvaro.sanchezmariscal@gmail.com"