language: groovy

jdk:
- oraclejdk7

branches:
  only:
  - master
  - develop
  - /^release.*$/
  - /^feature.*$/

services: memcached

script: ./test-app.sh

after_success: if [[ $TRAVIS_BRANCH == "master" ]] || [[ $TRAVIS_BRANCH =~ ^release.*$ ]]; then ./doc.sh; fi

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/ab2251f887cfa63260af
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

env:
  global:
    secure: NDX1oObVIHhG5zUZzhmL8m/601SFB2pE29dci1EcgKrYhdZf+50+Va/b0/7lNzYXnT76CwQmdkbsJmwqBh6+YO+SXcJFE13zudyGfZhLOwY+/oueQB8Up/gk2WbkY4FdIlo0XP/jl+atz4gR9EoAnKCYbdcjYj2lQnJ8ocDpi5U=
